package kz.edu.soccerhub.common.dto.client;

public enum ClientActivityType {
    CLIENT_CREATED,
    CLIENT_UPDATED,
    CLIENT_STATUS_CHANGED,
    STUDENT_LINKED,
    STUDENT_RELATION_UPDATED,
    STUDENT_RELATION_ENDED,
    CONTRACT_CREATED,
    CONTRACT_UPDATED,
    CONTRACT_EXTENDED,
    CONTRACT_CANCELLED,
    PAYMENT_CREATED,
    PAYMENT_CANCELLED
}
